services:
  node-app:
    build:
      context: ./back
      args:
        - NODE_ENV
    user: "node"
    env_file:
      - ./back/.env
    environment:
      - NODE_ENV=test
    develop:
      watch:
        - action: sync
          path: ./back
          target: /home/node/app
        - action: rebuild
          path: ./back/package.json
    command: "npm run test"
