services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV
    user: "node"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=test
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: .
          target: /home/node/app
        - action: rebuild
          path: package.json
    command: "npm run test"

  mongo:
    image: mongo
    attach: false
    env_file:
      - ./.env
    volumes:
      - mongo-db-data:/data/db
      - mongo-db-config:/data/configdb

volumes:
  mongo-db-data:
  mongo-db-config:
