services:
  node-back-dev:
    build:
      context: ./back
      args:
        - NODE_ENV
    user: "node"
    env_file:
      - ./back/.env
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://username:password@mongo-dev:27017/
    ports:
      - "4000:4000"
    develop:
      watch:
        - action: sync
          path: ./back
          target: /home/node/app
        - action: rebuild
          path: ./back/package.json
    command: "npm run dev"
    depends_on:
      - mongo-dev

  node-front-dev:
    build:
      context: ./front
      args:
        - NODE_ENV
    user: "node"
    env_file:
      - ./front/.env
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./front
          target: /home/node/app
        - action: rebuild
          path: ./front/package.json
    command: "npm run dev"
    depends_on:
      - node-back-dev

  mongo-dev:
    image: mongo
    attach: false
    env_file:
      - ./back/.env
    volumes:
      - mongo-db-dev-data:/data/db
      - mongo-db-dev-config:/data/configdb

volumes:
  mongo-db-dev-data:
  mongo-db-dev-config:
