services:
  node-back:
    build:
      context: ./back
      args:
        - NODE_ENV
    user: "node"
    env_file:
      - ./back/.env
    environment:
      - NODE_ENV=development
    ports:
      - "4000:4000"
    develop:
      watch:
        - action: sync
          path: ./back
          target: /home/node/app
        - action: rebuild
          path: ./back/package.json
    command: "npm run dev"
    depends_on:
      - mongo

  node-front:
    build:
      context: ./front
      args:
        - NODE_ENV
    user: "node"
    env_file:
      - ./front/.env
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./front
          target: /home/node/app
        - action: rebuild
          path: ./front/package.json
    command: "npm run dev"
    depends_on:
      - node-back

  mongo:
    image: mongo
    attach: false
    env_file:
      - ./back/.env
    volumes:
      - mongo-db-data:/data/db
      - mongo-db-config:/data/configdb

volumes:
  mongo-db-data:
  mongo-db-config:
