### healthcheck
GET http://localhost:3000/health

### api-docs
GET http://localhost:3000/api-docs

### obtener_notif
GET http://localhost:3000/notificacion

### Depende de un id
### notif_sin_leer
GET http://localhost:3000/notificacion/68370c535198cf164a309d79/sinleer

### Depende de un id
### notif_leidas
GET http://localhost:3000/notificacion/68370c535198cf164a309d79/leida

### Depende de un id
### leer_notif
PUT http://localhost:3000/notificacion/leer/6837585414214f84c533d292

### obtener_reservas
GET http://localhost:3000/reserva

### Depende de varios ids
### hacer_reserva
POST http://localhost:3000/reserva
Content_Type: application/json

{
	"huespedReservador": "68373bd7d9fb3ff01386636d",
	"cantHuespedes": 3,
	"alojamiento": "68373bd7d9fb3ff013866381",
	"rangoFechas": {
		"fechaInicio": "2025-09-04T00:00:00.000Z",
		"fechaFin": "2025-09-05T00:00:00.000Z"
	},
	"precioPorNoche": 7000
}

### Depende de un id
### historial_reservas
GET http://localhost:3000/reserva/68374012eaba399eb9e6775f

### Depende de un id
### cancelar_reserva
PUT http://localhost:3000/reserva/cancelar/683741191147eaa392a16653

### Depende de un id
### modificar_reserva
PUT http://localhost:3000/reserva/6837168d68c25d97e8627e42
Content_Type: application/json

{
	"huespedReservador": "6837168d68c25d97e8627e2c",
	"cantHuespedes": 3,
	"alojamiento": "6837168d68c25d97e8627e40",
	"rangoFechas": {
		"fechaInicio": "2025-09-21T00:00:00.000Z",
		"fechaFin": "2025-09-23T00:00:00.000Z"
	},
	"precioPorNoche": 7000,
	"estado": "CONFIRMADA"
}

### Depende de un id
### confirmar_reserva
PUT http://localhost:3000/reserva/confirmar/6837585414214f84c533d2a6

### Depende de un id
### rechazar_reserva
PUT http://localhost:3000/reserva/rechazar/6837438b08f3ca1b23af7bc0

### obtener_alojamientos
GET http://localhost:3000/alojamientos

### Depende de un id
### obtener_alojamiento
GET http://localhost:3000/alojamientos/68376d695abb55bf3cbd8d97
