### healthcheck

GET http://localhost:4000/health HTTP/1.1

### api-docs

GET http://localhost:4000/api-docs HTTP/1.1

### obtener_notif

GET http://localhost:4000/notificacion HTTP/1.1

### obtener_usuarios

GET http://localhost:4000/usuario HTTP/1.1

### notif_sin_leer

GET http://localhost:4000/notificacion/68370c535198cf164a309d79/sinleer HTTP/1.1

### notif_leidas

GET http://localhost:4000/notificacion/68370c535198cf164a309d79/leida HTTP/1.1

### leer_notif

PUT http://localhost:4000/notificacion/leer/6837585414214f84c533d292 HTTP/1.1

### obtener_reservas

GET http://localhost:4000/reserva HTTP/1.1

### hacer_reserva

POST http://localhost:4000/reserva HTTP/1.1
Content_Type: application/json

{
	"huespedReservador": "68373bd7d9fb3ff01386636d",
	"cantHuespedes": 3,
	"alojamiento": "68373bd7d9fb3ff013866381",
	"rangoFechas": {
		"fechaInicio": "2025-09-04T00:00:00.000Z",
		"fechaFin": "2025-09-05T00:00:00.000Z"
	},
	"precioPorNoche": 7000
}

### historial_reservas

GET http://localhost:4000/reserva/68374012eaba399eb9e6775f HTTP/1.1

### cancelar_reserva

PUT http://localhost:4000/reserva/cancelar/683741191147eaa392a16653 HTTP/1.1

### modificar_reserva

PUT http://localhost:4000/reserva/6837168d68c25d97e8627e42 HTTP/1.1
Content_Type: application/json

{
	"huespedReservador": "6837168d68c25d97e8627e2c",
	"cantHuespedes": 3,
	"alojamiento": "6837168d68c25d97e8627e40",
	"rangoFechas": {
		"fechaInicio": "2025-09-21T00:00:00.000Z",
		"fechaFin": "2025-09-23T00:00:00.000Z"
	},
	"precioPorNoche": 7000,
	"estado": "CONFIRMADA"
}

### confirmar_reserva

PUT http://localhost:4000/reserva/confirmar/6837585414214f84c533d2a6 HTTP/1.1

### rechazar_reserva

PUT http://localhost:4000/reserva/rechazar/6837438b08f3ca1b23af7bc0 HTTP/1.1

### obtener_alojamientos

GET http://localhost:4000/alojamiento HTTP/1.1

### filtrar_alojamientos

GET http://localhost:4000/alojamiento?caractPedidas=PISCINA HTTP/1.1

### obtener_alojamiento

GET http://localhost:4000/alojamiento/68524181b444a51d22c7a3be HTTP/1.1
